version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  
  # Puppeteer Example
  test-puppeteer-3.0.4:
    working_directory: ~/app
    docker:
      - image: saucelabs/sauce-puppeteer:3.0.4-saucectl0.4.1
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Puppeteer Tests
          command: |
            saucectl run -c ./.sauce/puppeteer-3.0.4.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI
  
  test-puppeteer-2.0.2:
    working_directory: ~/app
    docker:
      - image: saucelabs/sauce-puppeteer:2.0.2-saucectl0.4.1
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Puppeteer Tests
          command: |
            saucectl run -c ./.sauce/puppeteer-2.0.2.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Playwright Example
  test-playwright:
    working_directory: ~/app
    docker:
      - image: saucelabs/sauce-playwright:1.0.1-saucectl0.4.1
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Playwright Tests
          command: |
            saucectl run -c ./.sauce/playwright.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-puppeteer:
          requires:
            - setup
      - test-playwright:
          requires:
            - setup
